### ISSUE TITLE
Cannot create a map from the custom SDF file.

### ISSUE THREAD

**Issue by harshbhatt99** [turtlebot/turtlebot4_simulator#63]
I am trying to create a map with custom SDF file but, when I launch the following commands, RViz doesn't show up the map generation and LIDAR data. SDF is loading correctly in Gazebo.

I have already added the SDF file name in the turtlebot_ignition.launch.py file.
In one terminal, I am ruuning

`ros2 launch turtlebot4_ignition_bringup turtlebot4_ignition.launch.py slam:=true nav2:=true rviz:=true`

In second terminal, I am running

`ros2 launch turtlebot4_navigation slam.launch.py`

I am following the tutorial [https://turtlebot.github.io/turtlebot4-user-manual/tutorials/generate_map.html](url)
This issue is already discussed partially in #47 and #54 but I could not find the concluding answer.

On the second terminal, I am getting this message.

`[sync_slam_toolbox_node-1] [INFO] [1703994353.087267383] [slam_toolbox]: Message Filter dropping message: frame 'turtlebot4/rplidar_link/rplidar' at time 9.075 for reason 'the timestamp on the message is earlier than all the data in the transform cache'`

I tried increasing the buffer size in slam.yaml but it doesn't seem to be working.

Here are the screenshots of the robot in Gazebo and RViz.
![turtlebot4_2](https://github.com/turtlebot/turtlebot4_simulator/assets/55428431/6da5f6f7-b511-4465-97b3-24d3c7bd24c1)
![turtlebot4_1](https://github.com/turtlebot/turtlebot4_simulator/assets/55428431/b3fd6673-eaeb-434d-b299-7c219a484e30)

And here are the screenshots of the terminal messages

![turtlebot4_terminal2](https://github.com/turtlebot/turtlebot4_simulator/assets/55428431/5c41815d-eef8-4c44-aa38-7fc07a8d0c1b)
![turtlebot4_terminal1](https://github.com/turtlebot/turtlebot4_simulator/assets/55428431/ffd8d09a-1792-40b4-8521-7e1e0c8606c5)

I tried to find the solutions from other issues and threads. I doubt if this has something related to the computational power of my system. Can you take a look and see if I am doing anything wrong or it's a system problem?

**Comment by hilary-luo** [comment]
@harshbhatt99 Apologies that this issue was missed. Are you still experiencing this issue? If so I will take a look

**Comment by harshbhatt99** [comment]
@hilary-luo Yes, I am still experiencing this issue.

**Comment by hilary-luo** [comment]
@harshbhatt99 the first thing that jumps out at me is that you seem to be launching slam twice. This would cause unpredictable results and would be the first thing to resolve. When you run: `ros2 launch turtlebot4_ignition_bringup turtlebot4_ignition.launch.py slam:=true nav2:=true rviz:=true` you are launching the simulation as well as slam, rviz and nav2. The generate map tutorial is set up for use with a physical robot, that is why it indicates for you to launch slam separately in its own window. If you want to launch slam separately then set slam to false in that command and then you can launch it separately in its own terminal window. Furthermore if you want to simplify your test then you could also set nav2 to false until you are ready to use it.

If this doesn't solve your issue, please update with the new error messages etc. It would also help if you copy and paste the output from the terminals so that we can see what it did up to the point (you can omit repeating messages, just note that they are repeated)

**Comment by ajjaya18** [comment]
@harshbhatt99 Hi, you work with humble or galactic? and I have a question, I try to create a new World with ros galactic and I have problems with this, can you give me advice or can you guide me please?; @hilary-luo hi I have problems with generate a map, my turtlebot4 don't recognize the objects in the world depot, I think you know about this, the map of this world is already created in the tutorial but when I try to do the same it doesn't work, it doesn't scan anything, do I have to add some plugin to my Rplidar or something like that? please answer me.

**Comment by ajjaya18** [comment]
![Captura de pantalla de 2024-03-04 19-41-02](https://github.com/turtlebot/turtlebot4_simulator/assets/93724428/da4b0cb0-6f06-4169-b69c-9c896af16478)
![Captura de pantalla de 2024-03-04 19-41-07](https://github.com/turtlebot/turtlebot4_simulator/assets/93724428/97a076f2-61ce-4a63-a3a0-f6eb962cc987)
![Captura de pantalla de 2024-03-04 19-41-33](https://github.com/turtlebot/turtlebot4_simulator/assets/93724428/30932109-4c07-4b6d-a4e0-c253f1a500fc)

**Comment by ajjaya18** [comment]
Can you help me please?

**Comment by hilary-luo** [comment]
This issue is being closed due to inactivity. @harshbhatt99 if you are still experiencing the issue, feel free to reopen this ticket when you are ready to continue the troubleshooting process.
