### ISSUE TITLE
Could not find a connection between 'odom' and 'base_link'

### ISSUE THREAD

**Issue by neubej01** [turtlebot/turtlebot4_simulator#77]
### Robot Model

Turtlebot4 Standard

### ROS distro

Humble

### Networking Configuration

I do not know

### OS

Ubuntu 22.04

### Built from source or installed?

Built from Source

### Package version

le-turtlebot4-simulator
Package: ros-humble-turtlebot4-simulator
Status: install ok installed
Priority: optional
Section: misc
Installed-Size: 41
Maintainer: rkreinin <rkreinin@clearpathrobotics.com>
Architecture: amd64
Version: 1.0.2-1jammy.20240518.065938
Depends: ros-humble-turtlebot4-ignition-bringup, ros-humble-turtlebot4-ignition-gui-plugins, ros-humble-turtlebot4-ignition-toolbox, ros-humble-ros-workspace
Description: TODO: Package description

### Expected behaviour

I want to run the simulation described in https://turtlebot.github.io/turtlebot4-user-manual/software/turtlebot4_simulator.html. I start the simulation with the command "ros2 launch turtlebot4_ignition_bringup turtlebot4_ignition.launch.py nav2:=true rviz:=true world:=maze". This will open an ignition simulation window and an Rviz window. When I hit the play button I should see a map in Rviz and the Lidar measurements. 

### Actual behaviour

As I go through the process, the windows open as expected. Then I click play on the simulator and nothing happens in Rviz. There is no map or lidar readings. 

### Error messages

```bash
[controller_server-47] [INFO] [1717445412.870737451] [local_costmap.local_costmap]: Timed out waiting for transform from base_link to odom to become available, tf error: Could not find a connection between 'odom' and 'base_link' because they are not part of the same tree.Tf has two or more unconnected trees.
```

### To Reproduce

Follow in instructions in the tutorial for the simulator. Specifically, those that install from source. Then run the simulator as instructed.

**Comment by smatarCPR** [comment]
Hello @neubej01 ,
Thank you for reaching out on the Turtlebot4 Simulator Github page. With regards to this matter we have a couple questions we would like clarified:
1. Since you have built from source, would it be possible to provide the hash that you have built. You can use the command `git rev-parse HEAD` command to determine the hash.
2. Would it be possible to provide the motivation for installing the simulation from source?
3. Are you able to switch/test out a debian installation of the simulator? If so, please do so and let us know if the same error occurs.
Looking forward to hearing from you soon.
Best Regards,
Saif

**Comment by smatarCPR** [comment]
Hello,
This issue is being closed due to inactivity. If you are still experiencing the issue, feel free to reopen this ticket when you are ready to continue the troubleshooting process.
Best Regards,
Saif
